# Generated by Django 2.2.1 on 2019-05-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_add_path_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FilePathField(path='C:/image/', verbose_name='Imagen de cabecera'),
        ),
    ]
