# Generated by Django 2.2.1 on 2019-05-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_modify_Post_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FilePathField(path='C:\\image\\', verbose_name='Imagen de cabecera'),
        ),
    ]
