# Generated by Django 2.2.1 on 2019-05-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20190516_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_image',
            field=models.FilePathField(null=True, path='C:\\Users\\basanta79\\Documents\\bootcamp\\07_py_django\\wordplease\\images', verbose_name='Imagen de cabecera'),
        ),
    ]
