# Generated by Django 2.2.1 on 2019-05-19 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20190519_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_time_pub',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de publicación'),
        ),
    ]
