# Generated by Django 2.2.1 on 2019-05-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20190520_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.URLField(null=True, verbose_name='Imagen de cabecera'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(verbose_name='Imagen de cabecera'),
        ),
    ]
